Listen = ":8080"
ServiceDir = "services"
ServiceTempDir = "tmp"

[Pages]
  "401" = "/pages/login.html"

[Users]
  admin = "$2a$10$MnmhGyn4pELBONBmkY.XDOcEXDUJjMYPtVnFrdTQLeJYPZCLEJFeS" # password: admin

[Services]
  [Services.default]
    Restart = "yes"
    RunAsUser = ""